### ISSUE TITLE
DDEV initializsation

### ISSUE THREAD

**Issue by garvinhicking** [TYPO3-Documentation/site-introduction#43] opened 2024-12-30 20:42 UTC
Readme states to do a "ddev start && make install".

However, the process needs some tuning. After a "composer install" ddev needs to be restarted.

Probalby tweak:

```
.PHONY: setup
setup:
        @echo "Please note: The password to use during the interactive setup is 'db'."
        ddev typo3 setup --force
        ddev typo3 extension:setup
        @echo "Please note: The password to use during the interactive setup is 'db'."```
```

into:

```
.PHONY: setup
setup:
       @echo "Restarting DDEV to ensure it can detect TYPO3 version and create additional.php"
       ddev restart
        @echo "Please note: The password to use during the interactive setup is 'db'."
        ddev typo3 setup --force
        ddev typo3 extension:setup
        @echo "Please note: The password to use during the interactive setup is 'db'."```
```

Untested yet. I fixed this myself by restarting DDEV and then running setup again.

However I still run into the issue that the typo3 console setup fails with:

```
In SetupCommand.php line 626:

  The given url for the site name is not valid! Please try again.
```

Unsure if this is a bug with TYPO3 v13?! I have an empty site tree after this and could log into TYPO3

**Comment by garvinhicking** [comment] 2024-12-30 20:44
It seems the "Initialization" of my_site_package is not executed. I must admit I don't know how/if I can manually import this through the CLI or so?

**Comment by garvinhicking** [comment] 2024-12-30 20:47
It seems that "my_site_package" has a site config with:

```
base: '/'
```

however in my base config/sites/main/config.yaml this was created:

```
base: 'https://site-introduction.ddev.site'
```

**Comment by garvinhicking** [comment] 2024-12-30 20:53
SetupCommand.php at line 627 receives "no" as the URL for the Site...

**Comment by garvinhicking** [comment] 2024-12-30 20:58
It seems if I run this:

```
ddev typo3 setup --force --create-site 'https://site-introduction.ddev.site'
```

it works.

**Comment by garvinhicking** [comment] 2024-12-30 21:05
Actually it doesn't work, because I guess NO site should be created.

It seems that in setting `TYPO3_SETUP_CREATE_SITE=no` in the file `.ddev/docker-compose.context.yaml` is what triggers this.

The constant should better be left out completely, or set to an empty string "". Or the CLI could execute this:

```
ddev typo3 setup --force --create-site ''
```

BTW, it seems the backend_layout is missing some label of sorts, i get this in the backend then:

<img width="454" alt="Screenshot 2024-12-30 at 22 05 00" src="https://github.com/user-attachments/assets/8ec609d5-d03e-4db1-a9e3-d48be5ff4762" />

**Comment by garvinhicking** [comment] 2024-12-30 21:06
(I cannot pick "pagets__Default" from the list, it always reverts to the empty option, which leads to a malformed backend layout)

**Comment by garvinhicking** [comment] 2024-12-30 21:08
Ah, somehow the site configuration did not have the "my-site-package" set as a dependency?! I had to manually add this.

**Comment by linawolf** [comment] 2024-12-31 06:32
The fact that the set up command did not work is I think a core bug: https://forge.typo3.org/issues/105871

**Comment by linawolf** [comment] 2024-12-31 06:33
The backend layout issue is waiting to be merged to be fixed: https://github.com/TYPO3/get.typo3.org/pull/480 Benji is probably on vacation

**Comment by linawolf** [comment] 2024-12-31 06:35
The rest of the problems is probably caused by the site that you created so that site config etc did not match anymore?

In all my trials the additional.php was created automatically without a ddev restart. Mac issue?

**Comment by linawolf** [comment] 2024-12-31 07:30
@garvinhicking do these commits resolve your issues? can we close this issue?

**Closed by linawolf** 2024-12-31 07:30 UTC

**Comment by fe-hicking** [comment] 2024-12-31 07:42
Yes, looks good!
